// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_IhcGHZcjgYcweBbhfB8Ai1eI4XQ3Q4',
    appId: '1:458253485832:web:3512dd5232ab0efbd40ebd',
    messagingSenderId: '458253485832',
    projectId: 'setlist-e921f',
    authDomain: 'setlist-e921f.firebaseapp.com',
    databaseURL: 'https://setlist-e921f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setlist-e921f.appspot.com',
    measurementId: 'G-4FSC0X9GE9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_IhcGHZcjgYcweBbhfB8Ai1eI4XQ3Q4',
    appId: '1:458253485832:web:3512dd5232ab0efbd40ebd',
    messagingSenderId: '458253485832',
    projectId: 'setlist-e921f',
    authDomain: 'setlist-e921f.firebaseapp.com',
    databaseURL: 'https://setlist-e921f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setlist-e921f.appspot.com',
    measurementId: 'G-4FSC0X9GE9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKCDx83t8NSrHAjfdlVctnmwAYH7ts4Y',
    appId: '1:458253485832:ios:069fb8de52c1af2bd40ebd',
    messagingSenderId: '458253485832',
    projectId: 'setlist-e921f',
    databaseURL: 'https://setlist-e921f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setlist-e921f.appspot.com',
    iosBundleId: 'com.example.setlist',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLd2rxUaTxIzwOaYCnmEX6QAHJrxdm-B0',
    appId: '1:458253485832:android:9df44f344a2c379dd40ebd',
    messagingSenderId: '458253485832',
    projectId: 'setlist-e921f',
    databaseURL: 'https://setlist-e921f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'setlist-e921f.appspot.com',
  );

}